### ISSUE TITLE
Permission Denial: starting Intent

### ISSUE THREAD

**Issue by funcoding** [Udinic/AccountAuthenticator#8]
I imported the project in Android Studio. When I press ADDACCOUNT, I get the following message
```
03-21 22:39:01.899  12718-12735/com.udinic.accounts_example W/Binder﹕ Caught a RuntimeException from the binder stub implementation.
    java.lang.SecurityException: Permission Denial: starting Intent { cmp=com.udinic.accounts_authenticator_example.test/com.udinic.accounts_authenticator_example.authentication.AuthenticatorActivity (has extras) } from ProcessRecord{37027392 12718:com.udinic.accounts_example/u0a315} (pid=12718, uid=10315) not exported from uid 10286
            at android.os.Parcel.readException(Parcel.java:1540)
            at android.os.Parcel.readException(Parcel.java:1493)
            at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2433)
            at android.app.Instrumentation.execStartActivity(Instrumentation.java:1547)
            at android.app.Activity.startActivityForResult(Activity.java:3746)
            at android.app.Activity.startActivityForResult(Activity.java:3707)
            at android.app.Activity.startActivity(Activity.java:4027)
            at android.app.Activity.startActivity(Activity.java:3989)
            at android.accounts.AccountManager$AmsTask$Response.onResult(AccountManager.java:1710)
            at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:59)
            at android.os.Binder.execTransact(Binder.java:446)
```

**Comment by Leaking** [comment]
Hello,Just serveral minite ago,I fix the same problem,I don't know my reason is the same as yours.

My reason is I have install 2 apk with 2 different package name.So it can't choose which package's LoginActivity.

**Comment by taekhoon** [comment]
I'm not sure but why don't you try that you require permissions for 'android.permission.AUTHENTICATE_ACCOUNTS' ?

**Comment by santoki-darshan** [comment]
> Hello,Just serveral minite ago,I fix the same problem,I don't know my reason is the same as yours.
> 
> My reason is I have install 2 apk with 2 different package name.So it can't choose which package's LoginActivity.

It works fine with 1st app I installed but with 2nd one gives "Permission Denial" error

**Comment by ashukhushi** [comment]
@santoki-darshan-I have also facing same issue.please help me to resolve

**Comment by santoki-darshan** [comment]
> @santoki-darshan-I have also facing same issue.please help me to resolve

Try using different signin-config for apps
